ALTER TYPE "RelationshipStage" ADD VALUE IF NOT EXISTS 'CLOSE_FRIEND';
ALTER TYPE "RelationshipStage" ADD VALUE IF NOT EXISTS 'ROMANTIC_INTEREST';
ALTER TYPE "RelationshipStage" ADD VALUE IF NOT EXISTS 'DATING';
ALTER TYPE "RelationshipStage" ADD VALUE IF NOT EXISTS 'COMMITTED';
ALTER TYPE "RelationshipStage" ADD VALUE IF NOT EXISTS 'SOULMATE';
