import * as THREE from 'three';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';
import { RoomEnvironment } from 'three/examples/jsm/environments/RoomEnvironment.js';
import { RoundedBoxGeometry } from 'three/examples/jsm/geometries/RoundedBoxGeometry.js';
import { EffectComposer } from 'three/examples/jsm/postprocessing/EffectComposer.js';
import { RenderPass } from 'three/examples/jsm/postprocessing/RenderPass.js';
import { UnrealBloomPass } from 'three/examples/jsm/postprocessing/UnrealBloomPass.js';
import { OutputPass } from 'three/examples/jsm/postprocessing/OutputPass.js';
import { VRMHumanBoneName, VRMLoaderPlugin, VRMUtils } from '@pixiv/three-vrm';
import { VRMAnimationLoaderPlugin, createVRMAnimationClip } from '@pixiv/three-vrm-animation';

// ---------------------------------------------------------------------------
// timeline (generated by engine.planner via demo/generate_dinner_timeline.py)
// ---------------------------------------------------------------------------
const timeline = await (await fetch('/demo/vtuber_life_web/dinner_timeline.json')).json();
const BEATS = timeline.beats;
const EVENTS = timeline.events;
const DURATION = timeline.meta.duration_s;

const USER_POS = new THREE.Vector3(0.05, 1.32, -3.05); // where the (camera) user sits

// models face -Z at rotation.y = 0, so the yaw that faces direction (dx, dz) is:
const facing = (dx, dz) => Math.atan2(-dx, -dz);

// Scene blocking (waypoints + what each station does) is inherently scene-specific
// and stays here; identity (model/color/name/height) comes from the timeline JSON,
// which in turn comes from configs/characters.json.
const SCENE_LAYOUT = {
  luna: {
    waypoints: [
      { t: 0.0, x: -1.30, z: 0.74, h: 0 },
      { t: 8.6, x: -1.30, z: 0.74, h: 0 },
      { t: 10.6, x: -0.66, z: -0.42, h: 0 },
      { t: 30.0, x: -0.66, z: -0.42, h: 0 },
    ],
    activity: (t) => (t < 8.6 ? 'sketch' : 'talk'),
  },
  kai: {
    waypoints: [
      { t: 0.0, x: -0.36, z: 0.14, h: 0 },
      { t: 21.0, x: -0.36, z: 0.14, h: 0 },
      { t: 23.4, x: 0.55, z: 0.06, h: 1.2 },
      { t: 30.0, x: 0.55, z: 0.06, h: 1.2 },
    ],
    activity: (t) => (t < 21.0 ? 'cook' : 'talk'),
  },
  pipo: {
    waypoints: [
      { t: 0.0, x: 1.62, z: -0.5, h: -1.19 },
      { t: 23.6, x: 1.62, z: -0.5, h: -1.19 },
      { t: 25.6, x: 1.05, z: -0.62, h: 1.68 },
      { t: 30.0, x: 1.05, z: -0.62, h: 1.68 },
    ],
    activity: (t) => (t < 23.6 ? 'scan' : 'talk'),
  },
};

const FALLBACK_SPOTS = [[-1.0, 0.3], [0.0, 0.2], [1.2, -0.3]];

const CHARACTERS = {};
timeline.agents.forEach((agentMeta, index) => {
  const embodiment = agentMeta.embodiment ?? {};
  const spot = FALLBACK_SPOTS[index % FALLBACK_SPOTS.length];
  const layout = SCENE_LAYOUT[agentMeta.id] ?? {
    waypoints: [
      { t: 0.0, x: spot[0], z: spot[1], h: 0 },
      { t: 30.0, x: spot[0], z: spot[1], h: 0 },
    ],
    activity: () => 'talk',
  };
  CHARACTERS[agentMeta.id] = {
    id: agentMeta.id,
    name: agentMeta.name,
    role: agentMeta.role_label || agentMeta.archetype || '',
    color: agentMeta.color || '#8ecae6',
    kind: embodiment.kind ?? 'vrm',
    model: embodiment.model,
    targetHeight: embodiment.target_height ?? 1.6,
    pose: embodiment.pose ?? { upperZ: 1.3, upperX: -0.08, lowerX: -0.3 },
    ...layout,
  };
});

// ---------------------------------------------------------------------------
// renderer / scene
// ---------------------------------------------------------------------------
const canvas = document.querySelector('#scene');
if (window.innerWidth >= 1600) document.body.classList.add('hd');
const scene = new THREE.Scene();
scene.background = makeBackdropTexture();
scene.fog = new THREE.Fog(0x0b1119, 6.5, 12.5);

const renderer = new THREE.WebGLRenderer({ canvas, antialias: true, preserveDrawingBuffer: true });
renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
renderer.setSize(window.innerWidth, window.innerHeight);
renderer.outputColorSpace = THREE.SRGBColorSpace;
renderer.toneMapping = THREE.ACESFilmicToneMapping;
renderer.toneMappingExposure = 0.78;
renderer.shadowMap.enabled = true;
renderer.shadowMap.type = THREE.PCFSoftShadowMap;

const pmrem = new THREE.PMREMGenerator(renderer);
scene.environment = pmrem.fromScene(new RoomEnvironment(), 0.04).texture;

const camera = new THREE.PerspectiveCamera(31, window.innerWidth / window.innerHeight, 0.1, 100);
camera.position.set(2.8, 1.6, -4.8);
camera.lookAt(0, 0.8, 0);

const composer = new EffectComposer(renderer);
composer.addPass(new RenderPass(scene, camera));
const bloomPass = new UnrealBloomPass(new THREE.Vector2(window.innerWidth, window.innerHeight), 0.07, 0.3, 1.32);
composer.addPass(bloomPass);
composer.addPass(new OutputPass());

// lighting: warm interior against cool city night
const hemi = new THREE.HemisphereLight(0xf2f8ff, 0x2a201a, 0.5);
scene.add(hemi);
const keyLight = new THREE.DirectionalLight(0xffdcae, 0.95);
keyLight.position.set(-2.6, 4.6, -2.8);
keyLight.castShadow = true;
keyLight.shadow.mapSize.set(2048, 2048);
keyLight.shadow.camera.left = -4; keyLight.shadow.camera.right = 4;
keyLight.shadow.camera.top = 4; keyLight.shadow.camera.bottom = -4;
scene.add(keyLight);
const coolRim = new THREE.PointLight(0x7fc4ff, 2.6, 6.5);
coolRim.position.set(2.4, 1.9, 1.2);
scene.add(coolRim);
const warmKitchen = new THREE.PointLight(0xffa668, 1.15, 4.0);
warmKitchen.position.set(-0.4, 1.95, -0.6);
scene.add(warmKitchen);
const deskGlow = new THREE.PointLight(0xa8d4ff, 1.4, 3.0);
deskGlow.position.set(-1.5, 1.1, 0.3);
scene.add(deskGlow);

buildApartment(scene);
const sceneProps = buildSceneProps(scene);

// ---------------------------------------------------------------------------
// character loading
// ---------------------------------------------------------------------------
const loader = new GLTFLoader();
loader.register((parser) => new VRMLoaderPlugin(parser));

// VRMA 动捕：录制是逐帧 setTime 驱动，必须在 ready 前预载全部所需动作
const vrmaLoader = new GLTFLoader();
vrmaLoader.register((parser) => new VRMAnimationLoaderPlugin(parser));
const vrmaLib = {};
const performNames = [...new Set(BEATS
  .filter((b) => (b.step ?? '').startsWith('perform:'))
  .map((b) => b.step.split(':')[1]))];
await Promise.all(performNames.map(async (name) => {
  const gltf = await vrmaLoader.loadAsync(`/assets/animations/vrma_${name}.vrma`);
  vrmaLib[name] = gltf.userData.vrmAnimations?.[0] ?? null;
}));
// 最后一个无台词表演 beat 的起点 = 机器人挥手时刻（不再写死 28.4）
const WAVE_AT = BEATS.filter((b) => !b.text).map((b) => b.start).pop() ?? 28.4;

const agents = {};
await Promise.all(Object.values(CHARACTERS).map(async (config) => {
  if (config.kind === 'vrm') {
    agents[config.id] = await loadVrmAgent(config);
  } else {
    agents[config.id] = await loadRobotAgent(config);
  }
}));

let lastAnimT = 0;
let planRewritten = false;
let lastShotName = 'wide';
document.querySelector('#loading').classList.add('hidden');
initHud();
window.addEventListener('resize', onResize);

async function loadVrmAgent(config) {
  const gltf = await loader.loadAsync(config.model);
  const vrm = gltf.userData.vrm;
  VRMUtils.removeUnnecessaryVertices(gltf.scene);
  VRMUtils.combineSkeletons(gltf.scene);
  VRMUtils.rotateVRM0(vrm);
  vrm.scene.traverse((obj) => {
    obj.frustumCulled = false;
    if (obj.isMesh) {
      obj.castShadow = true;
      obj.receiveShadow = false;
      if (obj.material) { obj.material.envMapIntensity = 0.5; obj.material.needsUpdate = true; }
    }
  });
  const box = new THREE.Box3().setFromObject(vrm.scene);
  const size = box.getSize(new THREE.Vector3());
  vrm.scene.scale.setScalar(config.targetHeight / Math.max(0.1, size.y));
  const scaled = new THREE.Box3().setFromObject(vrm.scene);
  vrm.scene.userData.floorOffset = -scaled.min.y;
  scene.add(vrm.scene);
  // eye-tracking target: eyes lead the head toward whoever is being looked at
  const gazeObj = new THREE.Object3D();
  scene.add(gazeObj);
  if (vrm.lookAt) vrm.lookAt.target = gazeObj;
  return {
    ...config, vrm, root: vrm.scene, headWorld: new THREE.Vector3(),
    gazeObj, gazePos: new THREE.Vector3(), gazeWeight: 0, smoothHeading: null,
  };
}

async function loadRobotAgent(config) {
  const gltf = await loader.loadAsync(config.model);
  const root = gltf.scene;
  root.traverse((obj) => {
    obj.frustumCulled = false;
    if (obj.isMesh) { obj.castShadow = true; }
  });
  const box = new THREE.Box3().setFromObject(root);
  const size = box.getSize(new THREE.Vector3());
  root.scale.setScalar(config.targetHeight / Math.max(0.1, size.y));
  const scaled = new THREE.Box3().setFromObject(root);
  root.userData.floorOffset = -scaled.min.y;
  scene.add(root);

  const mixer = new THREE.AnimationMixer(root);
  const actions = {};
  gltf.animations.forEach((clip) => { actions[clip.name] = mixer.clipAction(clip); });
  const idle = actions.Idle;
  if (idle) { idle.play(); }
  let headBone = null;
  root.traverse((obj) => { if (!headBone && obj.isBone && /head/i.test(obj.name)) headBone = obj; });
  return {
    ...config, root, mixer, actions, headBone,
    currentAction: 'Idle', headWorld: new THREE.Vector3(),
    gazePos: new THREE.Vector3(), gazeWeight: 0, smoothHeading: null,
  };
}

// ---------------------------------------------------------------------------
// main loop
// ---------------------------------------------------------------------------
function animate() {
  const t = window.__recordTime !== undefined ? Number(window.__recordTime) : (performance.now() / 1000) % DURATION;
  updateScene(t);
  composer.render();
  window.__soulforgeFrameReady = true;
  requestAnimationFrame(animate);
}

function updateScene(t) {
  const dt = THREE.MathUtils.clamp(t - lastAnimT >= 0 ? t - lastAnimT : 1 / 24, 0.001, 0.12);
  const beat = BEATS.find((b) => t >= b.start && t < b.end) ?? null;
  const frames = {};
  for (const agent of Object.values(agents)) {
    frames[agent.id] = motionFrame(agent, t);
  }
  applyBeat(beat, frames, t);

  for (const agent of Object.values(agents)) {
    const frame = frames[agent.id];

    // temporal smoothing: bodies turn over ~0.3s instead of snapping on beat edges
    if (frame.moving || agent.smoothHeading == null) {
      agent.smoothHeading = frame.heading;
    } else {
      agent.smoothHeading = lerpAngle(agent.smoothHeading, frame.heading, 1 - Math.exp(-dt * 7));
    }
    frame.heading = agent.smoothHeading;

    // gaze fades in/out and the aim point glides between targets
    const headY = (agent.root.userData.floorOffset ?? 0) + agent.targetHeight * 0.9;
    const ahead = new THREE.Vector3(
      frame.x - Math.sin(frame.heading) * 2.5, headY, frame.z - Math.cos(frame.heading) * 2.5,
    );
    const aim = frame.gazeTarget ?? ahead;
    if (agent.gazeWeight <= 0.001 && frame.gazeTarget) agent.gazePos.copy(aim);
    agent.gazePos.lerp(aim, 1 - Math.exp(-dt * 8));
    agent.gazeWeight += ((frame.gazeTarget ? 1 : 0) - agent.gazeWeight) * (1 - Math.exp(-dt * 6));
    if (agent.gazeObj) agent.gazeObj.position.copy(agent.gazePos);

    agent.root.position.set(frame.x, agent.root.userData.floorOffset ?? 0, frame.z);
    agent.root.rotation.y = frame.heading;
    if (agent.kind === 'vrm') {
      animateVrm(agent, frame, t);
    } else {
      animateRobot(agent, frame, t, dt);
    }
    agent.headWorld.set(frame.x, headY, frame.z);
  }

  updateSceneProps(t, frames);
  updateHud(beat, frames, t);
  updateCamera(beat, t);
  lastAnimT = t;
}

// ---------------------------------------------------------------------------
// motion: waypoint interpolation + beat-driven gaze / turn-taking
// ---------------------------------------------------------------------------
function motionFrame(agent, t) {
  const wp = agent.waypoints;
  let a = wp[0]; let b = wp[wp.length - 1];
  for (let i = 0; i < wp.length - 1; i += 1) {
    if (t >= wp[i].t && t <= wp[i + 1].t) { a = wp[i]; b = wp[i + 1]; break; }
  }
  const span = Math.max(0.001, b.t - a.t);
  const raw = THREE.MathUtils.clamp((t - a.t) / span, 0, 1);
  const k = smoothstep(raw);
  const moving = raw > 0 && raw < 1 && (Math.hypot(b.x - a.x, b.z - a.z) > 0.05);
  const x = THREE.MathUtils.lerp(a.x, b.x, k);
  const z = THREE.MathUtils.lerp(a.z, b.z, k);
  let heading = moving ? facing(b.x - a.x, b.z - a.z) : lerpAngle(a.h, b.h, k);
  return {
    x, z, heading, moving,
    activity: agent.activity(t),
    speaking: false, listening: false,
    gazeTarget: null, // Vector3
    bodyTurn: 0,
  };
}

function applyBeat(beat, frames, t) {
  if (!beat) return;
  const speakerFrame = frames[beat.speaker];
  if (speakerFrame) {
    speakerFrame.speaking = beat.text.length > 0;
    const target = beat.targets[0];
    const pos = targetPosition(target, frames);
    if (pos && !speakerFrame.moving) {
      speakerFrame.gazeTarget = pos;
      // partially turn the body toward the target, fully turn the head
      const want = facing(pos.x - speakerFrame.x, pos.z - speakerFrame.z);
      const turn = beat.speaker === 'pipo' ? 0.9 : (speakerFrame.activity === 'talk' ? 0.5 : 0.35);
      speakerFrame.heading = lerpAngle(speakerFrame.heading, want, turn);
    }
  }
  beat.targets.forEach((id) => {
    const frame = frames[id];
    if (!frame || frame.moving) return;
    frame.listening = true;
    frame.beatStart = beat.start;
    const pos = targetPosition(beat.speaker, frames);
    if (pos) {
      frame.gazeTarget = pos;
      const want = facing(pos.x - frame.x, pos.z - frame.z);
      frame.heading = lerpAngle(frame.heading, want, frame.activity === 'talk' ? 0.45 : 0.2);
    }
  });
  // non-speaking third agent glances at the speaker too (soft social presence)
  Object.entries(frames).forEach(([id, frame]) => {
    if (id === beat.speaker || beat.targets.includes(id) || frame.moving) return;
    const pos = targetPosition(beat.speaker, frames);
    if (pos) frame.gazeTarget = pos;
  });
}

function targetPosition(id, frames) {
  if (id === 'user') return USER_POS.clone();
  const frame = frames[id];
  const agent = agents[id];
  if (!frame || !agent) return null;
  return new THREE.Vector3(frame.x, (agent.root.userData.floorOffset ?? 0) + agent.targetHeight * 0.88, frame.z);
}

// ---------------------------------------------------------------------------
// VRM animation
// ---------------------------------------------------------------------------
function animateVrm(agent, frame, t) {
  const vrm = agent.vrm;
  vrm.humanoid.resetNormalizedPose();

  // 动捕表演：beat.step === perform:<Name> 时动捕全权接管该角色骨骼（确定性：
  // 逐帧 mixer.setTime，可任意时刻重放），口型/眨眼仍在下方表情段生效
  const beat = BEATS.find((b) => t >= b.start && t < b.end
    && b.speaker === agent.id && (b.step ?? '').startsWith('perform:'));
  if (beat) {
    const name = beat.step.split(':')[1];
    if (vrmaLib[name]) {
      if (agent.vrmaName !== name) {
        agent.vrmaName = name;
        agent.vrmaMixer = new THREE.AnimationMixer(vrm.scene);
        const clip = createVRMAnimationClip(vrmaLib[name], vrm);
        agent.vrmaClipDur = clip.duration;
        agent.vrmaMixer.clipAction(clip).play();
      }
      // Goodbye 的前 1.2s 是从展开位起手，观感像 T-pose——跳过展开直接进挥手段
      const clipOffset = name === 'Goodbye' ? 1.2 : 0;
      agent.vrmaMixer.setTime(Math.min(t - beat.start + clipOffset, agent.vrmaClipDur - 1e-3));
      applyFaceAndFinish(agent, frame, t);
      return;
    }
  } else if (agent.vrmaName) {
    agent.vrmaName = null;
    agent.vrmaMixer = null;
  }
  const s = Math.sin;
  const phase = agent.id === 'luna' ? 0.0 : 2.1;
  const gait = s(t * 6.2 + phase);
  const breath = s(t * 1.7 + phase) * 0.03;
  const pose = agent.pose;

  let chestX = breath;
  let chestY = s(t * 0.8 + phase) * 0.03;
  let headX = s(t * 0.6 + phase) * 0.05;
  let headY = s(t * 0.45 + phase) * 0.08;
  let headZ = s(t * 0.5 + phase) * 0.03;
  let lUpX = pose.upperX; let rUpX = pose.upperX;
  let lUpZ = pose.upperZ; let rUpZ = -pose.upperZ;
  let lLoX = pose.lowerX; let rLoX = pose.lowerX;

  if (frame.moving) {
    lUpX = pose.upperX + 0.22 * gait;
    rUpX = pose.upperX - 0.22 * gait;
  } else if (frame.activity === 'cook') {
    // phased cooking: stir ~3s, lift the spatula and inspect ~1.4s, stir again
    const phase = (t * 0.9) % 5;
    const inspecting = phase > 3.0 && phase < 4.4;
    const stir = t * 5.2;
    if (inspecting) {
      rUpX = 0.66;
      rUpZ = -pose.upperZ + 0.14;
      rLoX = 1.15;
      headX = 0.30 + 0.02 * s(t * 1.4);   // peer into the pan
      chestX = 0.14 + breath;
    } else {
      rUpX = 0.52 + 0.07 * s(stir);
      rUpZ = -pose.upperZ + 0.10;
      rLoX = 0.92 + 0.14 * s(stir);
      headX = 0.16 + 0.02 * s(t * 2.2);
      chestX = 0.08 + breath;
    }
    lUpX = 0.4;
    lUpZ = pose.upperZ - 0.06;
    lLoX = 0.7;
  } else if (frame.activity === 'sketch') {
    const stroke = t * 3.6;
    rUpX = 0.24 + 0.03 * s(stroke);
    rUpZ = -pose.upperZ + 0.06;
    rLoX = 1.12 + 0.08 * s(stroke);
    lUpX = 0.20;
    lUpZ = pose.upperZ - 0.04;
    lLoX = 1.05;
    chestX = 0.10 + breath;
    headX = 0.26 + 0.02 * s(t * 1.6);
  } else if (frame.activity === 'talk') {
    if (frame.speaking) {
      const g = t * 4.4;
      lUpX = 0.15 + 0.05 * s(g);
      rUpX = 0.18 + 0.06 * s(g + 0.9);
      lUpZ = pose.upperZ - 0.1;
      rUpZ = -pose.upperZ + 0.14;
      lLoX = 0.5 + 0.09 * s(g);
      rLoX = 0.58 + 0.10 * s(g + 0.9);
      chestY += 0.03 * s(t * 2.6);
    } else {
      // attentive rest: hands folded low in front
      lUpX = 0.18;
      rUpX = 0.18;
      lLoX = 0.88;
      rLoX = 0.88;
      lUpZ = pose.upperZ - 0.04;
      rUpZ = -pose.upperZ + 0.04;
    }
  }

  if (frame.listening && !frame.speaking) {
    headX += 0.02 + 0.015 * s(t * 2.4); // small engaged tilt
    // acknowledgement nod right after the speaker starts talking
    if (frame.beatStart !== undefined) {
      const since = Math.max(0, t - frame.beatStart);
      headX += 0.09 * Math.exp(-since * 1.6) * Math.max(0, s(since * 9));
    }
  }

  // gaze: eyes (vrm.lookAt) lead, head follows smoothly with gazeWeight
  const w = agent.gazeWeight;
  if (w > 0.01) {
    const dx = agent.gazePos.x - frame.x;
    const dz = agent.gazePos.z - frame.z;
    const dy = agent.gazePos.y - agent.targetHeight * 0.88;
    let yaw = facing(dx, dz) - frame.heading;
    yaw = Math.atan2(Math.sin(yaw), Math.cos(yaw));
    const dist = Math.hypot(dx, dz);
    const pitch = -Math.atan2(dy, Math.max(0.3, dist));
    headY = headY * (1 - w) + THREE.MathUtils.clamp(yaw * 0.7, -0.85, 0.85) * w;
    headX = headX * (1 - w) + (THREE.MathUtils.clamp(pitch * 0.6, -0.4, 0.45)
      + (frame.listening ? 0.02 * s(t * 2.4) : 0)) * w;
    setBone(vrm, VRMHumanBoneName.Neck, [
      s(t * 0.7 + phase) * 0.04 * (1 - w),
      s(t * 0.5 + phase) * 0.09 * (1 - w) + THREE.MathUtils.clamp(yaw * 0.25, -0.4, 0.4) * w,
      0,
    ]);
  } else {
    setBone(vrm, VRMHumanBoneName.Neck, [s(t * 0.7 + phase) * 0.04, s(t * 0.5 + phase) * 0.09, 0]);
  }

  setBone(vrm, VRMHumanBoneName.Hips, [
    0,
    frame.moving ? 0 : 0.025 * s(t * 0.45 + phase),          // slow weight shift
    frame.moving ? gait * 0.04 : breath * 0.6,
  ]);
  setBone(vrm, VRMHumanBoneName.Chest, [chestX, chestY, 0]);
  setBone(vrm, VRMHumanBoneName.Head, [headX, headY, headZ]);
  setBone(vrm, VRMHumanBoneName.LeftUpperArm, [lUpX, 0.05, lUpZ]);
  setBone(vrm, VRMHumanBoneName.RightUpperArm, [rUpX, -0.05, rUpZ]);
  setBone(vrm, VRMHumanBoneName.LeftLowerArm, [lLoX + (frame.moving ? 0.12 * gait : 0), 0, 0.10]);
  setBone(vrm, VRMHumanBoneName.RightLowerArm, [rLoX + (frame.moving ? -0.12 * gait : 0), 0, -0.10]);
  setBone(vrm, VRMHumanBoneName.LeftUpperLeg, [frame.moving ? -0.36 * gait : 0, 0, 0]);
  setBone(vrm, VRMHumanBoneName.RightUpperLeg, [frame.moving ? 0.36 * gait : 0, 0, 0]);
  setBone(vrm, VRMHumanBoneName.LeftLowerLeg, [frame.moving ? 0.26 * Math.max(0, gait) : 0, 0, 0]);
  setBone(vrm, VRMHumanBoneName.RightLowerLeg, [frame.moving ? 0.26 * Math.max(0, -gait) : 0, 0, 0]);

  // relaxed finger curl so hands never read as stiff paddles; working hand grips harder
  const gripR = frame.activity === 'cook' || frame.activity === 'sketch' ? 0.62 : 0.3;
  const gripL = frame.activity === 'sketch' ? 0.5 : 0.28;
  curlFingers(vrm, 'Left', gripL + 0.03 * s(t * 1.3 + phase));
  curlFingers(vrm, 'Right', gripR + 0.03 * s(t * 1.5 + phase));

  applyFaceAndFinish(agent, frame, t);
}

function applyFaceAndFinish(agent, frame, t) {
  // face: blink + lipsync + mood（动捕表演时同样生效）
  const vrm = agent.vrm;
  const s = Math.sin;
  const em = vrm.expressionManager;
  if (em) {
    const blinkCycle = (t + (agent.id === 'luna' ? 0 : 1.4)) % 3.4;
    const blink = blinkCycle < 0.13 ? Math.sin((blinkCycle / 0.13) * Math.PI) : 0;
    setExpr(em, 'blink', blink);
    const mouth = frame.speaking ? 0.28 + 0.22 * Math.abs(s(t * 12.5)) + 0.12 * Math.abs(s(t * 7.3)) : 0;
    setExpr(em, 'aa', mouth);
    const warm = frame.speaking || frame.listening ? 0.28 : 0.15;
    setExpr(em, 'happy', agent.id === 'luna' ? warm + 0.05 : warm);
    setExpr(em, 'relaxed', frame.activity === 'talk' ? 0.2 : 0.3);
  }
  vrm.update(1 / 60);
}

function setExpr(manager, name, value) {
  if (manager.getExpressionTrackName?.(name) == null && !manager.expressionMap?.[name]) return;
  manager.setValue(name, value);
}

function setBone(vrm, boneName, euler) {
  const node = vrm.humanoid.getNormalizedBoneNode(boneName);
  if (!node) return;
  node.rotation.set(euler[0], euler[1], euler[2]);
}

const FINGER_SEGMENTS = [
  ['Index', [0.75, 1.0, 0.6]],
  ['Middle', [0.85, 1.0, 0.6]],
  ['Ring', [0.9, 1.0, 0.65]],
  ['Little', [0.95, 1.0, 0.7]],
];

function curlFingers(vrm, side, amount) {
  // left-hand curl is +Z in normalized space (mirrors the arm-lowering sign), right is -Z
  const sign = side === 'Left' ? 1 : -1;
  for (const [finger, weights] of FINGER_SEGMENTS) {
    ['Proximal', 'Intermediate', 'Distal'].forEach((segment, i) => {
      const node = vrm.humanoid.getNormalizedBoneNode(`${side.toLowerCase()}${finger}${segment}`);
      if (node) node.rotation.set(0, 0, sign * amount * weights[i]);
    });
  }
  const thumb = vrm.humanoid.getNormalizedBoneNode(`${side.toLowerCase()}ThumbProximal`);
  if (thumb) thumb.rotation.set(0, sign * amount * 0.3, 0);
}

// ---------------------------------------------------------------------------
// robot animation (RobotExpressive: AnimationMixer clips + head aim)
// ---------------------------------------------------------------------------
function animateRobot(agent, frame, t, dt) {
  // --- locomotion: weight-blend Idle<->Walking by actual speed, sync stride
  const dx = frame.x - (agent.prevX ?? frame.x);
  const dz = frame.z - (agent.prevZ ?? frame.z);
  const speed = Math.hypot(dx, dz) / Math.max(dt, 0.001);
  agent.prevX = frame.x; agent.prevZ = frame.z;
  agent.smoothSpeed = (agent.smoothSpeed ?? 0)
    + (speed - (agent.smoothSpeed ?? 0)) * (1 - Math.exp(-dt * 9));

  const idle = agent.actions.Idle;
  const walk = agent.actions.Walking;
  if (idle && walk && !agent.locoInit) {
    agent.locoInit = true;
    idle.play();
    walk.play();
    walk.setEffectiveWeight(0);
  }
  const NOMINAL = 0.5; // m/s at timeScale 1 — tuned to RobotExpressive stride
  const walkW = THREE.MathUtils.clamp(agent.smoothSpeed / NOMINAL, 0, 1);
  if (walk) {
    walk.setEffectiveWeight(walkW);
    walk.timeScale = THREE.MathUtils.clamp(agent.smoothSpeed / NOMINAL, 0.55, 1.5);
  }
  if (idle) idle.setEffectiveWeight(1 - walkW * 0.85);

  // --- one-shots: nod once when starting a line; thumbs-up; final wave
  let oneShot = null;
  if (t >= WAVE_AT) oneShot = 'Wave';
  else if (t >= WAVE_AT - 2.6 && t < WAVE_AT - 0.5) oneShot = 'ThumbsUp'; // acknowledges Kai
  else if (frame.speaking && !agent.wasSpeaking) oneShot = 'Yes';
  agent.wasSpeaking = frame.speaking;

  if (oneShot && agent.currentOneShot !== oneShot && agent.actions[oneShot]) {
    const action = agent.actions[oneShot];
    action.reset();
    action.setLoop(THREE.LoopOnce, 1);
    action.clampWhenFinished = oneShot === 'Wave';
    action.fadeIn(0.18).play();
    agent.currentOneShot = oneShot;
    agent.oneShotUntil = t + action.getClip().duration - 0.22;
  }
  if (agent.currentOneShot && t > agent.oneShotUntil) {
    if (agent.currentOneShot !== 'Wave') agent.actions[agent.currentOneShot]?.fadeOut(0.22);
    agent.currentOneShot = null;
  }

  agent.mixer.update(dt);

  // --- secondary motion on the root: bank into turns, idle bob, talk sway
  let turnRate = frame.heading - (agent.prevHeading ?? frame.heading);
  turnRate = Math.atan2(Math.sin(turnRate), Math.cos(turnRate)) / Math.max(dt, 0.001);
  agent.prevHeading = frame.heading;
  agent.smoothBank = (agent.smoothBank ?? 0)
    + (THREE.MathUtils.clamp(-turnRate * 0.05, -0.1, 0.1) - (agent.smoothBank ?? 0))
    * (1 - Math.exp(-dt * 6));
  agent.root.rotation.z = agent.smoothBank;
  if (walkW < 0.2) {
    agent.root.position.y += 0.006 * Math.sin(t * 2.1);          // gentle idle bob
    agent.root.rotation.y += 0.012 * Math.sin(t * 0.7 + 2.0);    // weight shift
  }
  if (frame.speaking) {
    agent.root.rotation.y += 0.028 * Math.sin(t * 3.0);          // conversational sway
  }

  // gaze: aim head bone after mixer update, smoothed via gazePos/gazeWeight
  if (agent.headBone && agent.gazeWeight > 0.01) {
    const dx = agent.gazePos.x - frame.x;
    const dz = agent.gazePos.z - frame.z;
    let yaw = facing(dx, dz) - frame.heading;
    yaw = Math.atan2(Math.sin(yaw), Math.cos(yaw));
    agent.headBone.rotation.y += THREE.MathUtils.clamp(yaw * 0.7, -0.9, 0.9) * agent.gazeWeight;
  } else if (agent.headBone && frame.activity === 'scan') {
    agent.headBone.rotation.x += 0.28 + 0.08 * Math.sin(t * 1.8); // inspect leaves
    agent.headBone.rotation.y += 0.25 * Math.sin(t * 0.9);
  }
}

// ---------------------------------------------------------------------------
// scene props: pan + steam + spatula, tablet, scan beam, watering can
// ---------------------------------------------------------------------------
function buildSceneProps(target) {
  const accentTeal = new THREE.Color('#63e6c8');
  const spatula = new THREE.Group();
  const spatulaHandle = new THREE.Mesh(
    new THREE.CylinderGeometry(0.012, 0.012, 0.24, 12),
    new THREE.MeshStandardMaterial({ color: 0x2a1c12, roughness: 0.5 }),
  );
  const spatulaHead = new THREE.Mesh(
    new RoundedBoxGeometry(0.06, 0.015, 0.08, 3, 0.006),
    new THREE.MeshStandardMaterial({ color: 0xd8dee6, metalness: 0.7, roughness: 0.3 }),
  );
  spatulaHead.position.y = -0.14;
  spatula.add(spatulaHandle, spatulaHead);
  spatula.castShadow = true;
  target.add(spatula);

  const scanBeam = new THREE.Mesh(
    new THREE.ConeGeometry(0.22, 0.7, 40, 1, true),
    new THREE.MeshBasicMaterial({ color: accentTeal, transparent: true, opacity: 0.16, depthWrite: false, side: THREE.DoubleSide }),
  );
  target.add(scanBeam);

  const scanRing = new THREE.Mesh(
    new THREE.RingGeometry(0.16, 0.19, 48),
    new THREE.MeshBasicMaterial({ color: accentTeal, transparent: true, opacity: 0.4, depthWrite: false, side: THREE.DoubleSide }),
  );
  scanRing.rotation.x = -Math.PI / 2;
  target.add(scanRing);

  // Luna's handheld sketch tablet
  const sketchPad = new THREE.Group();
  const padBody = new THREE.Mesh(new RoundedBoxGeometry(0.30, 0.022, 0.21, 4, 0.01),
    new THREE.MeshStandardMaterial({ color: 0x141d29, roughness: 0.4 }));
  const padScreen = new THREE.Mesh(new RoundedBoxGeometry(0.26, 0.012, 0.17, 4, 0.006),
    new THREE.MeshStandardMaterial({ color: 0x1c2c44, emissive: 0x8ecae6, emissiveIntensity: 0.55, roughness: 0.3 }));
  padScreen.position.y = 0.012;
  const padPen = new THREE.Mesh(new THREE.CylinderGeometry(0.006, 0.006, 0.13, 10),
    new THREE.MeshStandardMaterial({ color: 0xff9ec7 }));
  padPen.rotation.z = 1.1;
  padPen.position.set(0.1, 0.045, 0.02);
  sketchPad.add(padBody, padScreen, padPen);
  target.add(sketchPad);

  return { spatula, scanBeam, scanRing, sketchPad };
}

function updateSceneProps(t, frames) {
  const kai = frames.kai;
  const cookIntensity = kai.activity === 'cook' ? 1 : 0;
  sceneProps.spatula.visible = cookIntensityVisible(cookIntensity);
  if (cookIntensity) {
    const stir = t * 5.2;
    const phase = (t * 0.9) % 5;
    const inspecting = phase > 3.0 && phase < 4.4;
    sceneProps.spatula.scale.setScalar(0.68);
    if (inspecting) {
      // lifted out of the pan while Kai peers in
      sceneProps.spatula.position.set(-0.30, 1.14 + 0.01 * Math.sin(t * 2), -0.44);
      sceneProps.spatula.rotation.set(0.9, 0.3, 0.5);
    } else {
      // circular stir above the pan (pan sits at -0.36, 1.02, -0.40)
      sceneProps.spatula.position.set(
        -0.36 + Math.cos(stir) * 0.045,
        1.06 + 0.012 * Math.sin(stir * 2),
        -0.40 + Math.sin(stir) * 0.045,
      );
      sceneProps.spatula.rotation.set(0.5, -stir * 0.2, 0.35 + 0.1 * Math.sin(stir));
    }
  }

  // Luna holds the sketch pad while drawing
  const luna = frames.luna;
  const sketching = luna.activity === 'sketch' && !luna.moving;
  sceneProps.sketchPad.visible = sketching;
  if (sketching) {
    const fwdX = -Math.sin(luna.heading);
    const fwdZ = -Math.cos(luna.heading);
    sceneProps.sketchPad.position.set(
      luna.x + fwdX * 0.22, 0.92 + 0.008 * Math.sin(t * 3.6), luna.z + fwdZ * 0.22,
    );
    sceneProps.sketchPad.rotation.set(-0.42, luna.heading, 0.02 * Math.sin(t * 3.6));
  }

  const pipo = frames.pipo;
  const scanning = pipo.activity === 'scan' && !pipo.moving && !pipo.speaking;
  sceneProps.scanBeam.visible = scanning;
  sceneProps.scanRing.visible = scanning;
  if (scanning) {
    // beam from Pipo's face toward the plant cluster
    const from = new THREE.Vector3(pipo.x, 0.95, pipo.z);
    const to = new THREE.Vector3(2.28, 0.45, -0.78);
    const mid = from.clone().lerp(to, 0.55);
    sceneProps.scanBeam.position.copy(mid);
    sceneProps.scanBeam.lookAt(to);
    sceneProps.scanBeam.rotateX(-Math.PI / 2);
    sceneProps.scanBeam.material.opacity = 0.12 + 0.06 * Math.sin(t * 5);
    sceneProps.scanRing.position.set(to.x, 0.03, to.z);
    sceneProps.scanRing.scale.setScalar(1 + 0.12 * Math.sin(t * 4));
    sceneProps.scanRing.material.opacity = 0.3 + 0.14 * Math.sin(t * 4);
  }
}

function cookIntensityVisible(v) { return v > 0; }

// ---------------------------------------------------------------------------
// HUD
// ---------------------------------------------------------------------------
function initHud() {
  const tags = document.querySelector('#nametags');
  tags.innerHTML = Object.values(CHARACTERS).map((c) => `
    <div class="name-tag" id="tag-${c.id}" style="--agent:${c.color}">
      <span></span><strong>${c.name}</strong><small>${c.role}</small>
    </div>
  `).join('');
  renderPlan(timeline.plan_before, false);
}

function renderPlan(items, rewritten) {
  const panel = document.querySelector('#plan-items');
  panel.innerHTML = items.map((item, i) => `
    <div class="item ${rewritten && i < 2 ? 'new' : ''}">${item}</div>
  `).join('');
  const state = document.querySelector('#plan-state');
  state.textContent = rewritten ? 'REWRITTEN · 陪伴模式' : 'RUNNING';
  state.classList.toggle('rewritten', rewritten);
}

function updateHud(beat, frames, t) {
  // clock 20:47 -> 20:48
  const totalMin = 20 * 60 + 47 + (t / DURATION) * 1.6;
  document.querySelector('#clock').textContent =
    `${String(Math.floor(totalMin / 60)).padStart(2, '0')}:${String(Math.floor(totalMin) % 60).padStart(2, '0')}`;

  // dialogue bar (doubles as burned-in bilingual subtitles)
  const dialogue = document.querySelector('#dialogue');
  if (beat && beat.text) {
    dialogue.classList.add('active');
    dialogue.style.setProperty('--speaker', CHARACTERS[beat.speaker].color);
    document.querySelector('#dialogue-speaker').textContent = CHARACTERS[beat.speaker].name;
    document.querySelector('#dialogue-line').textContent = beat.text;
    document.querySelector('#dialogue-line-en').textContent = beat.text_en ?? '';
  } else {
    dialogue.classList.remove('active');
  }

  // brand cards: opening dissolves as Kai's first line lands; end card rises over the pull-back
  const title = document.querySelector('#titlecard');
  title.style.opacity = t < 1.0 ? '1' : String(Math.max(0, 1 - (t - 1.0) / 0.9));
  const endcard = document.querySelector('#endcard');
  endcard.style.opacity = String(THREE.MathUtils.clamp((t - (WAVE_AT + 0.2)) / 1.1, 0, 1));

  // event toast + plan rewrite
  const toast = document.querySelector('#event-toast');
  const activeEvent = EVENTS.find((e) => t >= e.t && t < e.t + 5.4);
  if (activeEvent) {
    toast.classList.add('visible');
    const isUser = activeEvent.source === 'user';
    document.querySelector('#event-text').textContent =
      isUser ? `🎤 用户：“${activeEvent.text}”` : `🌱 传感器：${activeEvent.text}`;
    const chipClass = activeEvent.impact === 'HIGH' || activeEvent.impact === 'CRITICAL' ? 'high' : 'low';
    document.querySelector('#event-decision').innerHTML =
      `<span class="chip ${chipClass}">IMPACT ${activeEvent.impact}</span>${activeEvent.decision}`;
  } else {
    toast.classList.remove('visible');
  }

  const userEvent = EVENTS.find((e) => e.source === 'user');
  if (userEvent && t >= userEvent.t + 1.2 && !planRewritten) {
    planRewritten = true;
    renderPlan(timeline.plan_after, true);
    document.querySelector('#plan-panel').classList.add('flash');
  }
  if (planRewritten && userEvent && t < userEvent.t + 1.2) {
    planRewritten = false; // allow deterministic re-render when scrubbing backwards
    renderPlan(timeline.plan_before, false);
    document.querySelector('#plan-panel').classList.remove('flash');
  }

  // nametags
  camera.updateMatrixWorld();
  Object.values(agents).forEach((agent) => {
    const tag = document.querySelector(`#tag-${agent.id}`);
    if (!tag) return;
    const world = agent.headWorld.clone();
    world.y += 0.24;
    world.project(camera);
    const x = (world.x * 0.5 + 0.5) * window.innerWidth;
    const y = (-world.y * 0.5 + 0.5) * window.innerHeight;
    tag.style.transform = `translate(${x}px, ${y}px) translate(-50%, -100%)`;
    tag.style.opacity = world.z < 1 && x > 0 && x < window.innerWidth ? '1' : '0';
  });
}

// ---------------------------------------------------------------------------
// cameras
// ---------------------------------------------------------------------------
const SHOTS = {
  wide: { pos: [2.75, 1.62, -4.7], look: [0.0, 0.85, 0.1], fov: 30, push: 0.5 },
  kitchen: { pos: [-1.55, 1.42, -2.7], look: [-0.34, 1.2, 0.1], fov: 33, push: 0.22 },
  desk: { pos: [-0.35, 1.35, -1.75], look: [-1.32, 1.12, 0.72], fov: 30, push: 0.14 },
  luna_close: { pos: [-0.6, 1.42, -2.35], look: [-0.66, 1.28, -0.42], fov: 25, push: 0.12 },
  kitchen_close: { pos: [0.42, 1.38, -2.25], look: [-0.36, 1.32, 0.1], fov: 27, push: 0.12 },
  plant: { pos: [-0.5, 1.35, -2.3], look: [1.55, 0.75, -0.5], fov: 27, push: 0.18 },
  two_shot: { pos: [-1.25, 1.5, -3.15], look: [0.62, 0.95, -0.1], fov: 34, push: 0.2 },
  group: { pos: [-1.7, 1.52, -2.95], look: [0.12, 1.0, -0.18], fov: 34, push: 0.18 },
  wide_end: { pos: [0.35, 1.72, -3.9], look: [0.05, 0.92, -0.1], fov: 31 },
};

let shotStartT = 0;

function updateCamera(beat, t) {
  let shotName = beat?.camera ?? lastShotName;
  if (t < 1.0) shotName = 'wide';
  if (!SHOTS[shotName]) shotName = 'wide';
  if (shotName !== lastShotName) shotStartT = t;
  lastShotName = shotName;
  const shot = SHOTS[shotName];

  let px = shot.pos[0]; let py = shot.pos[1]; let pz = shot.pos[2];
  if (shotName === 'wide_end') {
    const k = THREE.MathUtils.clamp((t - 27.4) / 2.6, 0, 1);
    pz -= k * 0.75; py += k * 0.1; // slow pull-back finale
  } else {
    // gentle eased push-in toward the subject over the life of the shot
    const p = THREE.MathUtils.clamp((t - shotStartT) / 5.0, 0, 1);
    const k = p * p * (3 - 2 * p);
    const push = (shot.push ?? 0.16) * k;
    const dir = new THREE.Vector3(shot.look[0] - px, shot.look[1] - py, shot.look[2] - pz).normalize();
    px += dir.x * push; py += dir.y * push; pz += dir.z * push;
  }
  // subtle handheld drift
  px += Math.sin(t * 0.5) * 0.02;
  py += Math.sin(t * 0.37 + 1.0) * 0.012;
  pz += Math.cos(t * 0.43) * 0.02;

  camera.fov = shot.fov;
  camera.position.set(px, py, pz);
  camera.lookAt(shot.look[0], shot.look[1], shot.look[2]);
  camera.updateProjectionMatrix();
}

// ---------------------------------------------------------------------------
// apartment (night, warm interior, cool city window)
// ---------------------------------------------------------------------------
function buildApartment(target) {
  const floorMat = new THREE.MeshStandardMaterial({ map: makeFloorTexture(), roughness: 0.5, metalness: 0.02 });
  const wallMat = new THREE.MeshStandardMaterial({ color: 0x27384e, roughness: 0.82 });
  const sideWallMat = new THREE.MeshStandardMaterial({ color: 0x18273a, roughness: 0.86 });
  const trimMat = new THREE.MeshStandardMaterial({ color: 0x101820, roughness: 0.44, metalness: 0.16 });
  const woodMat = new THREE.MeshStandardMaterial({ color: 0xa8754e, roughness: 0.44 });
  const darkWoodMat = new THREE.MeshStandardMaterial({ color: 0x473426, roughness: 0.46 });
  const blackMetalMat = new THREE.MeshStandardMaterial({ color: 0x10151d, roughness: 0.38, metalness: 0.28 });
  const cabinetMat = new THREE.MeshStandardMaterial({ color: 0x1d3145, roughness: 0.56, metalness: 0.08 });
  const fabricMat = new THREE.MeshStandardMaterial({ color: 0x44616a, roughness: 0.82 });
  const pillowMat = new THREE.MeshStandardMaterial({ color: 0xd38f6d, roughness: 0.78 });
  const rugMat = new THREE.MeshStandardMaterial({ color: 0x9d4a52, roughness: 0.9 });
  const plantPotMat = new THREE.MeshStandardMaterial({ color: 0x2a3c35, roughness: 0.72 });
  const leafMat = new THREE.MeshStandardMaterial({ color: 0x3ecf84, roughness: 0.7 });
  const screenMat = new THREE.MeshStandardMaterial({
    map: makeScreenTexture(), color: 0xffffff, emissive: 0x2cc7ff, emissiveIntensity: 0.4, roughness: 0.28,
  });
  const warmGlowMat = new THREE.MeshStandardMaterial({
    color: 0xc88a56, emissive: 0xff9f4d, emissiveIntensity: 0.14, roughness: 0.28,
  });

  addBox(target, [0, -0.045, 0], [5.35, 0.09, 3.7], floorMat, 0.035, true);
  addBox(target, [0, 1.05, 1.78], [5.35, 2.1, 0.11], wallMat, 0.018, true);
  addBox(target, [-2.67, 1.05, 0], [0.11, 2.1, 3.7], sideWallMat, 0.018, true);
  addBox(target, [2.67, 1.05, 0.22], [0.11, 2.1, 3.3], sideWallMat, 0.018, true);
  addBox(target, [0, 2.06, 0.02], [5.35, 0.08, 3.68], new THREE.MeshStandardMaterial({ color: 0x10151f, roughness: 0.74 }), 0.018, false);

  addBox(target, [0.1, 0.012, -0.3], [2.3, 0.024, 1.3], rugMat, 0.045, true);
  addBox(target, [0.1, 0.028, -0.3], [1.8, 0.012, 0.95], new THREE.MeshStandardMaterial({ color: 0xd28a72, roughness: 0.88 }), 0.04, true);

  addCityWindow(target, [1.12, 1.16, 1.71], [2.3, 1.15], trimMat);
  addNeonSign(target, [-1.35, 1.15, 1.7]);

  // kitchen: back counter + island (pan near Kai's side of the island)
  addBox(target, [-0.06, 0.4, 1.37], [1.52, 0.78, 0.24], cabinetMat, 0.035, true);
  addBox(target, [-0.06, 0.82, 1.23], [1.62, 0.1, 0.5], woodMat, 0.024, true);
  addBox(target, [-0.06, 1.16, 1.66], [1.8, 0.42, 0.08], new THREE.MeshStandardMaterial({ color: 0x99816c, roughness: 0.74 }), 0.014, true);
  addBox(target, [-0.62, 1.72, 1.62], [0.78, 0.34, 0.14], cabinetMat, 0.022, true);
  addBox(target, [0.24, 1.72, 1.62], [0.78, 0.34, 0.14], cabinetMat, 0.022, true);
  addBox(target, [-0.08, 1.02, 1.54], [1.62, 0.035, 0.025], warmGlowMat, 0.008, false);
  addBox(target, [-0.16, 0.54, -0.52], [1.36, 0.66, 0.58], cabinetMat, 0.045, true);
  addBox(target, [-0.16, 0.9, -0.52], [1.48, 0.1, 0.68], woodMat, 0.03, true);
  addBox(target, [-0.36, 0.96, -0.4], [0.34, 0.025, 0.24], blackMetalMat, 0.01, false);
  addBox(target, [0.22, 0.97, -0.5], [0.3, 0.035, 0.26], new THREE.MeshStandardMaterial({ color: 0xe4d3bd, roughness: 0.5 }), 0.012, true);
  const pan = new THREE.Mesh(new THREE.CylinderGeometry(0.15, 0.12, 0.05, 36), blackMetalMat);
  pan.position.set(-0.36, 1.0, -0.4);
  pan.castShadow = true;
  target.add(pan);
  const steamMat = new THREE.MeshBasicMaterial({ color: 0xffffff, transparent: true, opacity: 0.10, depthWrite: false });
  for (let i = 0; i < 4; i += 1) {
    const puff = new THREE.Mesh(new THREE.TorusGeometry(0.035 + i * 0.011, 0.004, 8, 30), steamMat.clone());
    puff.position.set(-0.36 + i * 0.015, 1.1 + i * 0.06, -0.4);
    puff.rotation.x = Math.PI / 2;
    target.add(puff);
  }
  addBarStool(target, [-0.66, 0.02, -1.06], darkWoodMat, blackMetalMat);
  addBarStool(target, [0.28, 0.02, -1.06], darkWoodMat, blackMetalMat);

  // desk station (Luna)
  addBox(target, [-1.44, 0.36, 0.34], [1.08, 0.12, 0.58], woodMat, 0.035, true);
  addBox(target, [-1.44, 0.19, 0.34], [0.96, 0.24, 0.46], darkWoodMat, 0.035, true);
  addBox(target, [-1.72, 0.66, 0.38], [0.46, 0.32, 0.035], screenMat, 0.016, true);
  addBox(target, [-1.3, 0.455, 0.28], [0.32, 0.028, 0.22], new THREE.MeshStandardMaterial({
    color: 0x17232f, emissive: 0x2cc7ff, emissiveIntensity: 0.5, roughness: 0.32,
  }), 0.01, false); // drawing tablet
  const pen = new THREE.Mesh(new THREE.CylinderGeometry(0.007, 0.007, 0.16, 10),
    new THREE.MeshStandardMaterial({ color: 0xff9ec7, emissive: 0x8a3d5c, emissiveIntensity: 0.2 }));
  pen.rotation.z = Math.PI / 2.6;
  pen.position.set(-1.18, 0.49, 0.3);
  target.add(pen);
  addBox(target, [-1.88, 0.56, 0.46], [0.12, 0.13, 0.12], new THREE.MeshStandardMaterial({ color: 0xf2eadc, roughness: 0.5 }), 0.02, true);

  // couch zone
  addBox(target, [1.48, 0.22, 0.58], [1.08, 0.34, 0.42], fabricMat, 0.055, true);
  addBox(target, [1.48, 0.55, 0.76], [1.12, 0.5, 0.12], fabricMat, 0.045, true);
  addBox(target, [0.88, 0.34, 0.58], [0.12, 0.44, 0.42], fabricMat, 0.04, true);
  addBox(target, [2.08, 0.34, 0.58], [0.12, 0.44, 0.42], fabricMat, 0.04, true);
  addBox(target, [1.26, 0.56, 0.46], [0.28, 0.18, 0.08], pillowMat, 0.028, true);
  addBox(target, [1.66, 0.56, 0.47], [0.3, 0.18, 0.08], new THREE.MeshStandardMaterial({ color: 0xead5aa, roughness: 0.78 }), 0.028, true);
  addBox(target, [1.26, 0.2, -0.1], [0.7, 0.14, 0.34], woodMat, 0.032, true);
  addBox(target, [1.26, 0.3, -0.1], [0.58, 0.035, 0.25], darkWoodMat, 0.018, true);
  [-0.16, 0.06, 0.2].forEach((offset, index) => {
    const candle = new THREE.Mesh(new THREE.CylinderGeometry(0.028, 0.03, 0.075, 20), warmGlowMat);
    candle.position.set(1.22 + offset, 0.38, -0.1 + (index - 1) * 0.06);
    candle.castShadow = true;
    target.add(candle);
    const light = new THREE.PointLight(0xffb76f, 0.22, 0.9);
    light.position.set(candle.position.x, candle.position.y + 0.1, candle.position.z);
    target.add(light);
  });

  // shelf + plants (Pipo's zone: big plant cluster bottom-right)
  addShelfWall(target, [-1.66, 1.46, 1.64], woodMat, darkWoodMat);
  // plant corner front-right: Pipo's care zone, visible from the main camera side
  addPlant(target, [2.28, 0.02, -0.78], plantPotMat, leafMat, 0.95);
  addPlant(target, [2.0, 0.02, -1.18], plantPotMat, leafMat, 0.6);
  addPlant(target, [-2.05, 0.02, 1.04], plantPotMat, leafMat, 0.8);
  addPlant(target, [2.15, 0.02, 1.32], plantPotMat, leafMat, 0.7);
  const wateringCan = new THREE.Mesh(new THREE.CylinderGeometry(0.07, 0.085, 0.14, 20),
    new THREE.MeshStandardMaterial({ color: 0x63e6c8, roughness: 0.4, metalness: 0.3 }));
  wateringCan.position.set(2.05, 0.09, -0.52);
  wateringCan.castShadow = true;
  target.add(wateringCan);

  addHangingLamp(target, [-0.22, 1.88, -0.02]);
  addHangingLamp(target, [1.42, 1.84, 0.74]);
  addFloorLamp(target, [-2.1, 0.02, -0.55], blackMetalMat, warmGlowMat);
}

function addCityWindow(target, pos, size, trimMat) {
  const city = new THREE.Mesh(new THREE.PlaneGeometry(size[0], size[1]),
    new THREE.MeshBasicMaterial({ map: makeCityTexture(), side: THREE.DoubleSide }));
  city.position.set(pos[0], pos[1], pos[2] - 0.022);
  target.add(city);
  addBox(target, [pos[0], pos[1] + size[1] / 2 + 0.035, pos[2] - 0.045], [size[0] + 0.12, 0.055, 0.035], trimMat, 0.01, true);
  addBox(target, [pos[0], pos[1] - size[1] / 2 - 0.035, pos[2] - 0.045], [size[0] + 0.12, 0.055, 0.035], trimMat, 0.01, true);
  addBox(target, [pos[0] - size[0] / 2 - 0.035, pos[1], pos[2] - 0.045], [0.055, size[1] + 0.12, 0.035], trimMat, 0.01, true);
  addBox(target, [pos[0] + size[0] / 2 + 0.035, pos[1], pos[2] - 0.045], [0.055, size[1] + 0.12, 0.035], trimMat, 0.01, true);
  [-0.25, 0.25].forEach((offset) => {
    addBox(target, [pos[0] + offset * size[0], pos[1], pos[2] - 0.09], [0.025, size[1] + 0.08, 0.025], trimMat, 0.004, false);
  });
  addBox(target, [pos[0], pos[1], pos[2] - 0.092], [size[0] + 0.08, 0.026, 0.025], trimMat, 0.004, false);
}

function addNeonSign(target, pos) {
  const sign = new THREE.Mesh(new THREE.PlaneGeometry(0.7, 0.36),
    new THREE.MeshBasicMaterial({ map: makeNeonTexture(), transparent: true, side: THREE.DoubleSide }));
  sign.position.set(pos[0], pos[1], pos[2] - 0.055);
  target.add(sign);
  const light = new THREE.PointLight(0x36d4ff, 1.6, 2.2);
  light.position.set(pos[0], pos[1], pos[2] - 0.45);
  target.add(light);
}

function addShelfWall(target, pos, woodMat, darkWoodMat) {
  for (let row = 0; row < 3; row += 1) {
    addBox(target, [pos[0], pos[1] - row * 0.28, pos[2]], [1.12, 0.045, 0.18], woodMat, 0.012, true);
  }
  [-0.54, 0.54].forEach((x) => addBox(target, [pos[0] + x, pos[1] - 0.28, pos[2]], [0.035, 0.6, 0.16], darkWoodMat, 0.01, true));
  for (let i = 0; i < 18; i += 1) {
    const row = i % 3;
    const col = Math.floor(i / 3);
    const mat = new THREE.MeshStandardMaterial({ color: [0x233d55, 0x8d5e49, 0xd8ba76, 0x63e6c8][i % 4], roughness: 0.6 });
    addBox(target, [pos[0] - 0.42 + col * 0.15, pos[1] + 0.05 - row * 0.28, pos[2] - 0.07],
      [0.055, 0.18 + (i % 2) * 0.04, 0.07], mat, 0.006, true);
  }
}

function addBarStool(target, pos, woodMat, metalMat) {
  const seat = new THREE.Mesh(new THREE.CylinderGeometry(0.16, 0.17, 0.055, 36), woodMat);
  seat.position.set(pos[0], 0.52, pos[2]);
  seat.castShadow = true;
  target.add(seat);
  const leg = new THREE.Mesh(new THREE.CylinderGeometry(0.018, 0.022, 0.48, 16), metalMat);
  leg.position.set(pos[0], 0.28, pos[2]);
  target.add(leg);
  const foot = new THREE.Mesh(new THREE.TorusGeometry(0.12, 0.01, 8, 32), metalMat);
  foot.position.set(pos[0], 0.12, pos[2]);
  foot.rotation.x = Math.PI / 2;
  target.add(foot);
}

function addFloorLamp(target, pos, metalMat, glowMat) {
  addBox(target, [pos[0], 0.62, pos[2]], [0.035, 1.2, 0.035], metalMat, 0.008, false);
  const shade = new THREE.Mesh(new THREE.CylinderGeometry(0.26, 0.34, 0.2, 40, 1, true), glowMat);
  shade.position.set(pos[0] + 0.28, 1.24, pos[2] - 0.16);
  shade.rotation.z = 0.35;
  target.add(shade);
  const light = new THREE.PointLight(0xffc38a, 0.9, 2.2);
  light.position.set(pos[0] + 0.2, 1.1, pos[2] - 0.18);
  target.add(light);
}

function addHangingLamp(target, pos) {
  const cordMat = new THREE.MeshStandardMaterial({ color: 0x273342, roughness: 0.45 });
  const glowMat = new THREE.MeshStandardMaterial({ color: 0xc99562, emissive: 0xffb25b, emissiveIntensity: 0.16, roughness: 0.28 });
  addBox(target, [pos[0], pos[1] + 0.18, pos[2]], [0.025, 0.38, 0.025], cordMat, 0.004, false);
  const shade = new THREE.Mesh(new THREE.CylinderGeometry(0.22, 0.32, 0.22, 40, 1, true), glowMat);
  shade.position.set(pos[0], pos[1], pos[2]);
  target.add(shade);
  const light = new THREE.PointLight(0xffc48a, 0.85, 3.2);
  light.position.set(pos[0], pos[1] - 0.16, pos[2]);
  target.add(light);
}

function addPlant(target, pos, potMat, leafMat, scale = 1) {
  const pot = new THREE.Mesh(new THREE.CylinderGeometry(0.12 * scale, 0.15 * scale, 0.24 * scale, 32), potMat);
  pot.position.set(pos[0], 0.12 * scale, pos[2]);
  pot.castShadow = true;
  pot.receiveShadow = true;
  target.add(pot);
  for (let i = 0; i < 6; i += 1) {
    const leaf = new THREE.Mesh(new THREE.SphereGeometry(0.15 * scale, 24, 14), leafMat);
    const angle = i * 1.15;
    leaf.scale.set(1.0, 0.36, 0.62);
    leaf.position.set(pos[0] + Math.cos(angle) * 0.11 * scale, 0.34 * scale + i * 0.02 * scale, pos[2] + Math.sin(angle) * 0.11 * scale);
    leaf.rotation.set(0.5, angle, 0.25);
    leaf.castShadow = true;
    target.add(leaf);
  }
}

function addBox(target, pos, scale, mat, radius = 0.025, shadow = false) {
  const mesh = new THREE.Mesh(new RoundedBoxGeometry(1, 1, 1, 5, radius), mat);
  mesh.position.set(pos[0], pos[1], pos[2]);
  mesh.scale.set(scale[0], scale[1], scale[2]);
  mesh.castShadow = shadow;
  mesh.receiveShadow = shadow;
  target.add(mesh);
  return mesh;
}

// ---------------------------------------------------------------------------
// canvas textures
// ---------------------------------------------------------------------------
function makeFloorTexture() {
  const c = document.createElement('canvas');
  c.width = 512; c.height = 512;
  const ctx = c.getContext('2d');
  ctx.fillStyle = '#5a4639';
  ctx.fillRect(0, 0, 512, 512);
  for (let y = 0; y < 512; y += 64) {
    for (let x = 0; x < 512; x += 128) {
      const offset = (y / 64) % 2 ? 64 : 0;
      const tone = 72 + ((x + y) % 5) * 8;
      ctx.fillStyle = `rgb(${tone + 24}, ${tone + 4}, ${tone - 10})`;
      ctx.fillRect((x + offset) % 512, y + 2, 124, 60);
    }
  }
  ctx.strokeStyle = 'rgba(20,14,10,0.45)';
  for (let y = 0; y <= 512; y += 64) {
    ctx.beginPath(); ctx.moveTo(0, y); ctx.lineTo(512, y); ctx.stroke();
  }
  const texture = new THREE.CanvasTexture(c);
  texture.wrapS = THREE.RepeatWrapping;
  texture.wrapT = THREE.RepeatWrapping;
  texture.repeat.set(2.8, 2.2);
  texture.colorSpace = THREE.SRGBColorSpace;
  return texture;
}

function makeCityTexture() {
  const c = document.createElement('canvas');
  c.width = 1024; c.height = 512;
  const ctx = c.getContext('2d');
  const gradient = ctx.createLinearGradient(0, 0, 0, 512);
  gradient.addColorStop(0, '#07101e');
  gradient.addColorStop(0.42, '#102642');
  gradient.addColorStop(1, '#050810');
  ctx.fillStyle = gradient;
  ctx.fillRect(0, 0, 1024, 512);
  for (let i = 0; i < 72; i += 1) {
    const x = (i * 139) % 1024;
    const y = (i * 83) % 260;
    ctx.fillStyle = i % 3 === 0 ? 'rgba(255,214,152,0.9)' : 'rgba(105,196,255,0.72)';
    ctx.fillRect(x, y, 2 + (i % 2), 2 + (i % 3));
  }
  for (let i = 0; i < 28; i += 1) {
    const x = i * 42 - 12;
    const w = 28 + (i % 5) * 12;
    const h = 120 + (i % 7) * 36;
    ctx.fillStyle = i % 2 ? '#0d1728' : '#101f33';
    ctx.fillRect(x, 512 - h, w, h);
    for (let yy = 512 - h + 16; yy < 500; yy += 22) {
      for (let xx = x + 8; xx < x + w - 8; xx += 14) {
        if ((xx + yy + i) % 4 === 0) continue;
        ctx.fillStyle = (xx + yy) % 3 === 0 ? 'rgba(255,188,110,0.85)' : 'rgba(84,190,255,0.62)';
        ctx.fillRect(xx, yy, 4, 6);
      }
    }
  }
  const texture = new THREE.CanvasTexture(c);
  texture.colorSpace = THREE.SRGBColorSpace;
  return texture;
}

function makeNeonTexture() {
  const c = document.createElement('canvas');
  c.width = 512; c.height = 256;
  const ctx = c.getContext('2d');
  ctx.font = '76px "Trebuchet MS", Arial, sans-serif';
  ctx.textAlign = 'center';
  ctx.textBaseline = 'middle';
  ctx.shadowColor = '#2ed8ff';
  ctx.shadowBlur = 22;
  ctx.strokeStyle = '#2ed8ff';
  ctx.lineWidth = 3;
  ctx.strokeText('Soul', 252, 90);
  ctx.strokeText('Forge', 252, 160);
  ctx.fillStyle = 'rgba(139,226,255,0.95)';
  ctx.fillText('Soul', 252, 90);
  ctx.fillText('Forge', 252, 160);
  const texture = new THREE.CanvasTexture(c);
  texture.colorSpace = THREE.SRGBColorSpace;
  return texture;
}

function makeScreenTexture() {
  const c = document.createElement('canvas');
  c.width = 512; c.height = 320;
  const ctx = c.getContext('2d');
  ctx.fillStyle = '#101827';
  ctx.fillRect(0, 0, 512, 320);
  // an in-progress illustration on Luna's screen
  ctx.fillStyle = '#1c2c44';
  ctx.fillRect(30, 30, 452, 260);
  ctx.strokeStyle = 'rgba(255,158,199,0.85)';
  ctx.lineWidth = 4;
  ctx.beginPath();
  ctx.arc(250, 150, 70, 0.2, Math.PI * 1.5);
  ctx.stroke();
  ctx.beginPath();
  ctx.moveTo(180, 230); ctx.quadraticCurveTo(250, 170, 330, 220);
  ctx.stroke();
  ctx.strokeStyle = 'rgba(142,202,230,0.7)';
  ctx.beginPath();
  ctx.moveTo(120, 90); ctx.quadraticCurveTo(200, 40, 300, 80);
  ctx.stroke();
  const texture = new THREE.CanvasTexture(c);
  texture.colorSpace = THREE.SRGBColorSpace;
  return texture;
}

function makeBackdropTexture() {
  const c = document.createElement('canvas');
  c.width = 1024; c.height = 1024;
  const ctx = c.getContext('2d');
  const gradient = ctx.createLinearGradient(0, 0, 0, 1024);
  gradient.addColorStop(0, '#0b111b');
  gradient.addColorStop(0.58, '#101923');
  gradient.addColorStop(1, '#070b10');
  ctx.fillStyle = gradient;
  ctx.fillRect(0, 0, 1024, 1024);
  const texture = new THREE.CanvasTexture(c);
  texture.colorSpace = THREE.SRGBColorSpace;
  return texture;
}

// ---------------------------------------------------------------------------
function smoothstep(x) {
  const v = Math.max(0, Math.min(1, x));
  return v * v * (3 - 2 * v);
}

function lerpAngle(a, b, k) {
  let diff = b - a;
  while (diff > Math.PI) diff -= Math.PI * 2;
  while (diff < -Math.PI) diff += Math.PI * 2;
  return a + diff * k;
}

function onResize() {
  camera.aspect = window.innerWidth / window.innerHeight;
  camera.updateProjectionMatrix();
  renderer.setSize(window.innerWidth, window.innerHeight);
  composer.setSize(window.innerWidth, window.innerHeight);
}

window.__soulforge = {
  ready: () => Object.keys(agents).length === Object.keys(CHARACTERS).length,
  setTime: (seconds) => {
    window.__recordTime = seconds;
    updateScene(seconds);
    composer.render();
    lastAnimT = seconds;
  },
};

animate();
